In [1]:
# 계좌 클래스 만들기 
# 변수 : 자산(asset), 이자율(interest)
# 함수 : 인출(draw), 입금(insert), 이자추가(add_interest)
# 인출시 자산이상의 돈을 인출할수 없습니다.

In [10]:
class Account():
    def __init__(self, asset = 0, interest = 1.05):
        self.asset = asset
        self.interest = interest
    
    def draw(self, money):
        if self.asset >= money:
            self.asset -= money
            print("{}원이 인출되었습니다.".format(money))
        else:
            print('인출금이 {}원 부족합니다'.format(money - self.asset))
            
    def insert(self, money):
        self.asset += money
        print("{}원이 입금 되었습니다.".format(money))
        
    def add_interest(self):
        self.asset *= self.interest
        print('이자가 지급되었습니다.')
        
    def __repr__(self):
        return 'account(asset : {}, interest : {})'.format(self.asset, self.interest)

In [11]:
account1 = Account(10000)

In [12]:
account1

account(asset : 10000, interest : 1.05)

In [13]:
account1.draw(12000)

인출금이 2000원 부족합니다


In [14]:
account1.draw(3000)

3000원이 인출되었습니다.


In [15]:
account1.asset

7000

In [16]:
account1.insert(5000)

5000원이 입금 되었습니다.


In [17]:
account1

account(asset : 12000, interest : 1.05)

In [18]:
account1.add_interest()

이자가 지급되었습니다.


In [19]:
account1

account(asset : 12600.0, interest : 1.05)

### Module Package
- 모듈 : 변수, 함수, 클래스를 모아놓은 (.py) 확장자를 가진 파일
- 패키지 : 모듈의 기능을 디렉토리별로 정리해 놓은 개념

### 1. 모듈 
- 모듈 생성
- 모듈 호출

In [22]:
!dir

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: CC15-C0FD

 C:\Users\user\fast 디렉터리

2021-05-04  오전 11:00    <DIR>          .
2021-05-04  오전 11:00    <DIR>          ..
2021-05-04  오전 10:32    <DIR>          .ipynb_checkpoints
2021-04-22  오후 03:23    <DIR>          03. 뉴욕(NYC) 택시수요 예측 Project
2021-04-19  오전 09:50    <DIR>          08. Ensemble 기법의 종류와 원리
2021-05-04  오전 08:50            35,204 Boston_house.csv
2021-05-04  오전 10:32            28,106 day 1.ipynb
2021-05-04  오전 11:00             5,233 day 2.ipynb
2021-05-04  오전 08:50           102,995 Personal Loan.csv
2021-05-04  오전 08:50           216,430 ToyotaCorolla.csv
2021-05-04  오전 09:41            48,889 Untitled.ipynb
2021-05-04  오전 10:57               583 Untitled1.ipynb
2021-04-30  오후 03:46    <DIR>          week 1
               7개 파일             437,440 바이트
               6개 디렉터리  67,157,479,424 바이트 남음


In [78]:
%%writefile dss.py
num = 1234

def disp1(msg):
    print('disp1', msg)
    
def disp2(mag):
    print('disp2', msg)
    
class Calc:
    def plus(self, *args):
        return sum(args)

Overwriting dss.py


In [82]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [83]:
%whos

Interactive namespace is empty.


In [84]:
# 모듈 호출 : import
import dss

In [85]:
%whos

Variable   Type      Data/Info
------------------------------
dss        module    <module 'dss' from 'C:\\U<...>ers\\user\\fast\\dss.py'>


In [86]:
dss.num

1234

In [87]:
dss.disp1('python')

disp1 python


In [88]:
calc = dss.Calc()

In [89]:
calc.plus(1,2,3,4)

TypeError: sum expected at most 2 arguments, got 4

In [90]:
import random

In [101]:
random.randint(1, 5)

5

In [102]:
# 모듈안에 특정 함수, 변수, 클래스 호출

In [103]:
# 장점 : dss.num 이렇게 안쓰고 바로 num으로 써도 됨
from dss import num,disp2

In [104]:
%whos

Variable   Type        Data/Info
--------------------------------
calc       Calc        <dss.Calc object at 0x00000287F3210688>
disp2      function    <function disp2 at 0x00000287F33B6558>
dss        module      <module 'dss' from 'C:\\U<...>ers\\user\\fast\\dss.py'>
num        int         1234
random     module      <module 'random' from 'C:<...>st_envs\\lib\\random.py'>


In [105]:
num

1234

In [109]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [110]:
# 모듈의 모든 변수를 가져옴
from dss import * 

In [111]:
%whos

Variable   Type        Data/Info
--------------------------------
Calc       type        <class 'dss.Calc'>
disp1      function    <function disp1 at 0x00000287F33B64C8>
disp2      function    <function disp2 at 0x00000287F33B6558>
num        int         1234


### 2. Package
- 패키지 생성
- 패키지 호출
- setup.py 패키지 설치 파일 만들기

In [ ]:
# 디렉토리 생성
!mkdir -p school/dss

In [ ]:
# 디렉토리 생성
!mkdir -p school/web

In [116]:
- tree 설치 mac
    - hombrew 설치
    - brew install tree

'C:\\Users\\user\\fast'

In [ ]:
!tree school

In [ ]:
# 패키지 사용시 디렉토리에 __init__.py 파일을 추가
# python 3.3버전 이상에서는 필요 없음

In [ ]:
!touch school/dss/__init__.py
!touch school/web/__init__.py

In [ ]:
!tree school

In [ ]:
%%writefile school/dss/data1.py

def plus2(*args):
    print('data2')
    return sum(args)

In [ ]:
%%writefile school/web/url.py

def make(url):
    return url if url[:7] == 'http://' else 'http://' + url

In [ ]:
!tree school/

In [1]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [ ]:
import school.dss.data1

In [ ]:
whos

In [ ]:
school.dss.data1.plus(1,2,3)

In [ ]:
import school.dss.data1 as dss
#import numpy as np

In [ ]:
dss.plus(1,2)

In [ ]:
#  school.web : 디렉토리
# url : 모듈
from school.web import url

In [ ]:
url.make('google.com')

In [ ]:
url.make('http://naver.com')

In [3]:
# 패키지의 위치 : 특정 디렉토리에 있는 패키지는 어디에서나 import 가능

In [4]:
import random

In [6]:
!dir

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: CC15-C0FD

 C:\Users\user\fast 디렉터리

2021-05-06  오후 04:12    <DIR>          .
2021-05-06  오후 04:12    <DIR>          ..
2021-05-04  오후 01:39    <DIR>          .ipynb_checkpoints
2021-04-22  오후 03:23    <DIR>          03. 뉴욕(NYC) 택시수요 예측 Project
2021-04-19  오전 09:50    <DIR>          08. Ensemble 기법의 종류와 원리
2021-05-04  오전 08:50            35,204 Boston_house.csv
2021-05-04  오전 10:32            28,106 day 1.ipynb
2021-05-06  오후 04:12            21,210 day2.ipynb
2021-05-04  오전 11:22               177 dss.py
2021-05-04  오전 08:50           102,995 Personal Loan.csv
2021-05-04  오전 08:50           216,430 ToyotaCorolla.csv
2021-05-04  오전 09:41            48,889 Untitled.ipynb
2021-05-05  오후 10:13            19,286 Untitled1.ipynb
2021-04-30  오후 03:46    <DIR>          week 1
2021-05-04  오전 11:18    <DIR>          __pycache__
               8개 파일             472,297 바이트
               7개 디렉터리  64,978,468,864 바이트 남음


In [7]:
import sys
for path in sys.path:
    print(path)

C:\Users\user\fast
C:\Users\user\.conda\envs\test_envs\python37.zip
C:\Users\user\.conda\envs\test_envs\DLLs
C:\Users\user\.conda\envs\test_envs\lib
C:\Users\user\.conda\envs\test_envs

C:\Users\user\.conda\envs\test_envs\lib\site-packages
C:\Users\user\.conda\envs\test_envs\lib\site-packages\win32
C:\Users\user\.conda\envs\test_envs\lib\site-packages\win32\lib
C:\Users\user\.conda\envs\test_envs\lib\site-packages\Pythonwin
C:\Users\user\.conda\envs\test_envs\lib\site-packages\IPython\extensions
C:\Users\user\.ipython


In [9]:
!dir C:\Users\user\.conda\envs\test_envs\lib

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: CC15-C0FD

 C:\Users\user\.conda\envs\test_envs\lib 디렉터리

2021-03-04  오전 09:48    <DIR>          .
2021-03-04  오전 09:48    <DIR>          ..
2021-02-16  오전 10:29             5,580 abc.py
2021-02-16  오전 10:29            32,814 aifc.py
2021-02-16  오전 10:29               477 antigravity.py
2021-02-16  오전 10:29            95,372 argparse.py
2021-02-16  오전 10:29            12,842 ast.py
2021-02-16  오전 10:29            11,328 asynchat.py
2021-03-04  오전 09:48    <DIR>          asyncio
2021-02-16  오전 10:29            20,118 asyncore.py
2021-02-16  오전 10:29            20,382 base64.py
2021-02-16  오전 10:29            31,730 bdb.py
2021-02-16  오전 10:29            13,954 binhex.py
2021-02-16  오전 10:29             2,557 bisect.py
2021-02-16  오전 10:29            12,410 bz2.py
2021-02-16  오전 10:29            24,826 calendar.py
2021-02-16  오전 10:29            35,040 cgi.py
2021-02-16  오전 10:29            12,018 cgitb.py
2021-02-16  오전 10:29             5,435 chunk.py

In [12]:
packages = !dir C:\Users\user\.conda\envs\test_envs\lib
len(packages)

212

### 예외처리
- 코드를 실행중에 에러가 발생한 경우 에러를 처리하는 방법
- try, except, finally, raise

In [16]:
# try, except : 에러가 발생해도 코드의 실행을 계속하고 싶을때
ls = [1,2,3]

In [17]:
print(ls[3])
print('done!')

IndexError: list index out of range

In [18]:
try:
    print(ls[3])
except Exception as e:
    print('error')
    print(e)
print('Done')

error
list index out of range
Done


In [21]:
#finally : try, except 구문 실행된 후 finally 구문이 실행
try:
    1/0
except:
    print('error')
finally:              # 에러가 발생해도 실행 에러가 발생하지 않아도 실행
    print('Done!')

error
Done!


In [22]:
# raise : 강제로 에러를 발생시키는 명령
try:
    1/0
except Exception as e:
    print('error')
    raise(e)
print('Done!')

error


ZeroDivisionError: division by zero

In [ ]:
# 에러 생성 : 10이상의 숫자가 입력되도록 하는 에러
# 10이하가 입력되면 에러
# LowNumber

In [23]:
class LowNumber(Exception):
    def __str__(self):
        return 'Number grater than 10'
    

In [24]:
def input_number(num):
    if num <= 10:
        raise LowNumber()
    print(num)

In [27]:
input_number(12)

12


In [26]:
input_number(8)

LowNumber: Number grater than 10

### Numpy
- 데이터는 행렬로 표현
- 행렬 데이터 빠르게 계산을 해야 합니다.
- 행렬 데이터 생성, 수정, 계싼등을 빠르게 처리해주는 패키지
- 특징
    - C, C++, 포트란으로 작성
    - 선형대수학을 빠르게 연산
        - 스칼라, 벡터, 메트릭스

In [28]:
import numpy as np

In [36]:
# 행렬데이터 생성
# ndarray : 한가지 데이터 타입만 값으로 사용이 가능
array = np.array([1,2,3])
print(type(array))
print(array)

<class 'numpy.ndarray'>
[1 2 3]


In [37]:
array2 = np.array(
    [[1,2,3],
    [4,5,6,]])
print(array2)
print(array2.ndim) # 2차원 행렬
print(array2.shape) # 행, 열

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [40]:
# 행렬의 모양(shape) 변경하기
print(array2.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [41]:
# 3차원
array2.reshape(3,2,1)

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [47]:
# 행렬 데이터의 선택 : offset index : masking
array2[1]

array([4, 5, 6])

In [48]:
array2[1][2]

6

In [50]:
array2[1,2] # array2[1][2]

6

In [51]:
# 데이터 수정

In [55]:
ls = [1,2,3]
ls[1] = 5
ls

[1, 5, 3]

In [53]:
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
array2[1][2] = 10
array2

array([[ 1,  2,  3],
       [ 4,  5, 10]])

In [59]:
# 브로드 캐스팅
array2[0] = 0
array2

In [61]:
array2[0] = [7,8,9]
array2

array([[ 7,  8,  9],
       [ 4,  5, 10]])

In [65]:
# 조건으로 선택
array2 > 7

array([[False,  True,  True],
       [False, False,  True]])

In [66]:
idx = array2 > 7
array2[idx]

array([ 8,  9, 10])

In [67]:
array2[idx] = 100
array2

array([[  7, 100, 100],
       [  4,   5, 100]])

In [68]:
# 행렬 데이터의 생성 2

In [69]:
data = np.zeros((2,3))
data

array([[0., 0., 0.],
       [0., 0., 0.]])

In [70]:
data.dtype

dtype('float64')

In [72]:
data2 = data.astype('int')
data2.dtype

dtype('int32')

In [77]:
data3 = np.ones((2,3))
data3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [78]:
# arange
np.arange(5)

array([0, 1, 2, 3, 4])

In [79]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [80]:
np.arange(5,10,2)

array([5, 7, 9])